"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FractieZetelVacature = exports.FractieZetelPersoon = exports.FractieZetel = exports.Fractie = exports.ActiviteitActor = void 0;
const ActiviteitActor_1 = require("../modal/ActiviteitActor");
Object.defineProperty(exports, "ActiviteitActor", { enumerable: true, get: function () { return ActiviteitActor_1.ActiviteitActor; } });
const Fractie_1 = require("../modal/Fractie");
Object.defineProperty(exports, "Fractie", { enumerable: true, get: function () { return Fractie_1.Fractie; } });
const FractieZetel_1 = require("../modal/FractieZetel");
Object.defineProperty(exports, "FractieZetel", { enumerable: true, get: function () { return FractieZetel_1.FractieZetel; } });
const FractieZetelPersoon_1 = require("../modal/FractieZetelPersoon");
Object.defineProperty(exports, "FractieZetelPersoon", { enumerable: true, get: function () { return FractieZetelPersoon_1.FractieZetelPersoon; } });
const FractieZetelVacature_1 = require("../modal/FractieZetelVacature");
Object.defineProperty(exports, "FractieZetelVacature", { enumerable: true, get: function () { return FractieZetelVacature_1.FractieZetelVacature; } });
