"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Verslag = exports.Vergadering = exports.Stemming = exports.FractieZetel = exports.Fractie = void 0;
const Fractie_1 = require("./Fractie");
Object.defineProperty(exports, "Fractie", { enumerable: true, get: function () { return Fractie_1.Fractie; } });
const FractieZetel_1 = require("./FractieZetel");
Object.defineProperty(exports, "FractieZetel", { enumerable: true, get: function () { return FractieZetel_1.FractieZetel; } });
const Stemming_1 = require("./Stemming");
Object.defineProperty(exports, "Stemming", { enumerable: true, get: function () { return Stemming_1.Stemming; } });
const Vergadering_1 = require("./Vergadering");
Object.defineProperty(exports, "Vergadering", { enumerable: true, get: function () { return Vergadering_1.Vergadering; } });
const Verslag_1 = require("./Verslag");
Object.defineProperty(exports, "Verslag", { enumerable: true, get: function () { return Verslag_1.Verslag; } });
